In [1]:
#class kavramı : oop de kullanılan bir yapıdır. 
# Aynı türdeki verileri oluşturmak için bir şablon görevi görür.

In [9]:
class Product:
    def __init__(self, name,price,stock):
        self.name = name
        self.price = price
        self.stock = stock
    def bilgi_ver(self):
        print(f'Ürünün adı : {self.name}, Değeri : {self.price}, Stoğu : {self.stock}')

    def __str__(self):
        return f'Ürünün adı : {self.name}, Değeri : {self.price}, Stoğu : {self.stock}'

In [10]:
urun1 = Product('Dyson Süpürge',25000,50)
urun1.bilgi_ver()

Ürünün adı : Dyson Süpürge, Değeri : 25000, Stoğu : 50


In [11]:
print(urun1)

Ürünün adı : Dyson Süpürge, Değeri : 25000, Stoğu : 50


In [12]:
# garaj  adında bir class ımız olsun garajdaki arabalarla alakalı işlemler yapalım.

In [22]:
class Garaj:
    def __init__(self,arabalar,name):
        self.arabalar = arabalar
        self.name = name
    def __len__(self):
        return len(self.arabalar)
    
    def __str__(self):
        return f'{self.name} garajındaki araçlar : {self.arabalar}'

In [24]:
# __len__(obje) : len fonksitonu çağrıldığı zaman bir class ın kendine göre özel davranışını ortaya kkoyar.
garaj1 = Garaj(arabalar=['Audi','BMW','Mercedes','Renault','Skoda'],name='Garaj 1')
garaj2 = Garaj(['Porsche','Lamborghini','Ferrari','Masserati'], name ="Garaj 2")


print(f'1. Garajdaki araba sayısı : {len(garaj1)}')
print(f'2. Garajdaki araba sayısı : {len(garaj2)}')

print(garaj1)
print(garaj2)

1. Garajdaki araba sayısı : 5
2. Garajdaki araba sayısı : 4
Garaj 1 garajındaki araçlar : ['Audi', 'BMW', 'Mercedes', 'Renault', 'Skoda']
Garaj 2 garajındaki araçlar : ['Porsche', 'Lamborghini', 'Ferrari', 'Masserati']


In [43]:
# getitem : bir class içerisindeki listenin hangi indexine erişmek istiyorsak kullandığımız fonksiyondur.
# setitem:  bir class içerisindeki listenin indexinde ki bir verinin değerini değiştirmek için kullanılır
# delitem : bir class içerisindeki listenin indexine göre silme işlemi yapar.
class Library:
    def __init__(self,name):
        self.books = ['Anna Karanina 1','Anna Karanina 2','Anna Karanina 3']
        self.name = name
        
    def __str__(self):
        return f'kütüphane adı : {self.name}, Kütüphane içerisindeki kitaplar : {self.books}'
    
    def __getitem__(self,index):
        return self.books[index]
    
    def __setitem__(self, index, yeni_kitap):
        self.books[index] = yeni_kitap
        
    def __delitem__(self, index):
        del self.books[index]
    

In [44]:
lib1 = Library('Üsküdar Kütüphanesi')
print(lib1)



kütüphane adı : Üsküdar Kütüphanesi, Kütüphane içerisindeki kitaplar : ['Anna Karanina 1', 'Anna Karanina 2', 'Anna Karanina 3']


In [45]:
print(lib1[0])

lib1[1]='Germinal'
print(lib1)

Anna Karanina 1
kütüphane adı : Üsküdar Kütüphanesi, Kütüphane içerisindeki kitaplar : ['Anna Karanina 1', 'Germinal', 'Anna Karanina 3']


In [46]:
del lib1[2]

In [47]:
print(lib1)

kütüphane adı : Üsküdar Kütüphanesi, Kütüphane içerisindeki kitaplar : ['Anna Karanina 1', 'Germinal']


In [48]:
# Bir şirket ile alakalı bilgiler bir şablonda tutulmak isteniyor. 
# Bu şablonda alanlar şu lekilde tutulmalı :
# Çalışanlar, şirketin_adı, şirketin_butcesi , sirketin_personel_maaşı
# Şirketin çalışanlarının listelenmesi
# şirketin kaç tane çalışanı var 
# Şirket ile alakalı bir bilgilendirme metni 
# şirketin kar da mı zararda mı olduğunu gösteren fonksiyon (sirket_butcesi> personel_maası zararda)

In [49]:
class Worker:
    def __init__(self, isim,maas):
        self.isim = isim
        self.maas = maas
    
    def __str__(self):
        return f'adı : {self.isim}, maaşı : {self.maas}'
    

In [57]:
class Company:
    def __init__(self, name, budget):
        self.name = name
        self.workers = []
        self.budget = budget
        
    def calisan_ekle(self, calisan_adi, calisan_maasi):
        worker = Worker(calisan_adi, calisan_maasi)
        self.workers.append(worker)
    
    
    def calisan_yazdir(self):
        for worker in self.workers:
            print(worker)
            
    def __len__(self):
        return len(self.workers)
    
    def __str__(self):
        return f'şirket adı : {self.name}, şirketin bütçesi : {self.budget}'
    
    
    def kar_zarar(self):
        calisan_butcesi = 0
        for worker in self.workers:
            calisan_butcesi += worker.maas
            
        print(f'Şirketin Bütcesi : {self.budget}')
        print(f'Çalışanların Maliyeti : {calisan_butcesi}')
        if calisan_butcesi> self.budget:
            fark = calisan_butcesi - self.budget
            print(f'{fark} TL Zarardasınız.')
        else:
            fark = self.budget - calisan_butcesi
            print(f'{fark} TL Kardasınız')
    
    

In [58]:
sirket = Company(name='Suez Yazılım',budget=3000000)
sirket.calisan_ekle("Cemil Dalar",85000)
sirket.calisan_ekle('Sidar Erzincan',150000)
sirket.calisan_ekle('Halil Erdoğan',100000)

In [59]:
sirket.calisan_yazdir()

adı : Cemil Dalar, maaşı : 85000
adı : Sidar Erzincan, maaşı : 150000
adı : Halil Erdoğan, maaşı : 100000


In [60]:
print(f'Şirketteki çalışan sayısı : {len(sirket)}')

Şirketteki çalışan sayısı : 3


In [61]:
print(sirket)

şirket adı : Suez Yazılım, şirketin bütçesi : 3000000


In [62]:
sirket.kar_zarar()

Şirketin Bütcesi : 3000000
Çalışanların Maliyeti : 335000
2665000 TL Kardasınız


In [72]:
class Person:
    def __init__(self, isim , yas):
        self.isim = isim
        self.yas = yas
    def __str__(self):
        return f'isim : {self.isim}, yaş : {self.yas}'
    
    def __eq__(self, other):    # equals
        return self.isim == other.isim and self.yas == other.yas
    
    # greather than
    def __gt__(self,other):
        return self.yas> other.yas

In [73]:
person1 = Person('deneme',25)
person2 = Person('deneme',25)

print(person1==person2)

True


In [75]:
person3 = Person('Buse Gönek',26)
person4 = Person('Deneme',27)
print(person3>person4)
print(person3<person4)

False
True


In [76]:
#13:07 de dersteyiz

In [91]:
class Tasit:
    def __init__(self, marka, model, max_hiz):
        self.marka =marka
        self.model = model
        self.max_hiz = max_hiz
        
    def bilgi_goster(self):
        print(f'Marka : {self.marka}, Model : {self.model}, Maksimum hız : {self.max_hiz} ')
class Araba(Tasit):
    def __init__(self, marka, model, max_hiz,kapi_sayisi):
        super().__init__(marka,model,max_hiz)
        self.kapi_sayisi = kapi_sayisi
        
    def kapi_saiyisi_goster(self):
        super().bilgi_goster()
        print(f'kapi sayısı : {self.kapi_sayisi}')
        
class Motosiklet(Tasit):
    def __init__(self, marka, model, max_hiz, kask_durumu):
        super().__init__(marka,model,max_hiz)
        self.kask_durumu = kask_durumu
        
        
    def kask_durumu_goster(self):
        super().bilgi_goster()
        print(f'Kask var mı : {self.kask_durumu}')

In [92]:
car = Araba('Bmw',2022,360,2)
ms1 = Motosiklet('Yamaha',2014,380,True)

car.kapi_saiyisi_goster()


ms1.kask_durumu_goster()

Marka : Bmw, Model : 2022, Maksimum hız : 360 
kapi sayısı : 2
Marka : Yamaha, Model : 2014, Maksimum hız : 380 
Kask var mı : True


## Numpy(Numerical Python)
### Çok boyutlu veya tek boyutlu diziler ile çalışırken daha rahat ve daha performans 
### odeaklı çalışmak istiyorsak kullanırız.

## Avantajları :
### C dili ile optimize edildiği için python listelerine göre daha hızlı ve az bellek tüketir

In [93]:
# 1 ... 1000000000
# 1 ... 1000000000

# 2 , 4 ,6 

In [4]:
import numpy as np
import time 

In [12]:
def python_version():
    start_time = time.time()
    liste1 = [i for i in range(100000000)]
    liste2 = [i for i in range(100000000)]
    
    toplam = [liste1[i]+ liste2[i] for i in range(len(liste1))]
    sure = time.time() - start_time
    print(f'Python versiyonu çalışma süresi : {sure}')

In [13]:
def numpy_version():
    start_time = time.time()
    array1 = np.arange(1,100000000)
    array2 = np.arange(1,100000000)
    sum_array = array1 + array2
    sure = time.time() - start_time
    print(f'Numpy versiyonu için geçen süre : {sure}')

In [14]:
python_version()
numpy_version()

Python versiyonu çalışma süresi : 36.99151349067688
Numpy versiyonu için geçen süre : 0.2967977523803711


In [15]:
list1 = [10,0,45,55,65]
list1

[10, 0, 45, 55, 65]

In [16]:
arr1 = np.array(list1)
arr1

array([10,  0, 45, 55, 65])

In [17]:
arr1.astype(float)

array([10.,  0., 45., 55., 65.])

In [18]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[1]

1

In [23]:
b = np.arange(0,101,10)
b

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
c = np.arange(100,-1,-10)
c

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0])

In [26]:
# [0,0,0,0,0]
zeros = np.zeros(5).astype(int)
zeros

array([0, 0, 0, 0, 0])

In [27]:
ones = np.ones(6).astype(int)
ones

array([1, 1, 1, 1, 1, 1])

In [28]:
# tekrarlı sayılar : repeat(tekrarlanacak_sayi, kaç_tane_yazsin)
repeat = np.repeat(25,6)
repeat

array([25, 25, 25, 25, 25, 25])

In [29]:
d = np.array([1,2,3,4,5])
repeat_d = np.repeat(d,3)
repeat_d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [30]:
sayilar= np.arange(1,21)
# e dizisindeki tek sayıları liste şeklinde tutan kodu yazınız.
tek_sayilar = []
for sayi in sayilar:
    if sayi %2 ==1:
        tek_sayilar.append(sayi)
tek_sayilar

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [31]:
tek_numpy = sayilar[sayilar % 2 ==1]
tek_numpy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
# linspace(baslangıç, bitiş , adet) : eşit aralıklarla kaç adet sayı eklenecekse kullanılan fonksiyondur. 

In [33]:
lns = np.linspace(20,50,4)
lns

array([20., 30., 40., 50.])

In [34]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [35]:
np.linspace(10,20,4).astype(int)

array([10, 13, 16, 20])

In [36]:
np.random.random(4)

array([0.07706547, 0.7301312 , 0.03114996, 0.36060964])

In [39]:
# randint : int random sayı üretir
np.random.randint(0,500,10)

array([324, 452, 274, 229, 258, 279,  55, 450, 483, 130])

In [42]:
np.random.seed(200)
np.random.randint(0,500,10)

array([282, 105, 272, 324, 298, 183, 332,  79, 345,  14])

In [44]:
np.random.uniform(5,25, size=(10))

array([ 5.05721183, 12.14847363, 23.19389771, 14.12161971, 24.63605418,
       22.34713981, 24.72055023, 23.46533413, 11.07386628, 21.92206981])

In [45]:
dizi2 = np.arange(1,20)
dizi2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
# min : ilgili dizinin minimum değerini alır
dizi2.min()

1

In [48]:
# max : ilgili dizinin maksimum değerini alır.
dizi2.max()

19

In [49]:
# sum : dizideki tüm elemanları toplar
dizi2.sum()

190

In [51]:
# dizi2 nin aritmetik ortalamasını hesaplayan kodu yazınız.
# 1. Yöntem 
mean = dizi2.sum()/ len(dizi2)
mean

10.0

In [52]:
#2. Yöntem
mean1 = dizi2.mean()
mean1

10.0

In [53]:
np.mean(dizi2)

10.0

In [55]:
dizi3 = np.array([1,99,8,7,5,-58,100,102,102])

print(f'dizi3 ün en büyük elemanının index numarası : {dizi3.argmax()}')
print(f'dizi3 ün en küçük elemanının index numarası : {dizi3.argmin()}')

dizi3 ün en büyük elemanının index numarası : 7
dizi3 ün en küçük elemanının index numarası : 5


In [56]:
# standart sapma : 
dizi3.std()

56.987328026110816

In [57]:
np.std(dizi3)

56.987328026110816

In [58]:
# varyasyon hesabı :
dizi3.var()

3247.5555555555557

In [59]:
np.var(dizi3)

3247.5555555555557

In [60]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
sum(sum(A))

45

In [63]:
A.sum()

45

In [64]:

np.amin(A, axis=0)

array([1, 2, 3])

In [66]:
np.amax(A , axis = 0)

array([7, 8, 9])

In [67]:
np.amin(A, axis=1)

array([1, 4, 7])

In [68]:
np.amax(A, axis=1)

array([3, 6, 9])

In [69]:
b = np.random.randint(10,20,30)
b

array([16, 10, 13, 16, 13, 18, 14, 10, 14, 12, 15, 12, 14, 10, 13, 17, 18,
       18, 13, 11, 18, 10, 14, 16, 13, 14, 14, 16, 12, 10])

In [70]:
# 1. indexten 3. indexe kadar elemanları ayrı bir listede tutmak
rule_list1 = b[1:4]
rule_list1

array([10, 13, 16])

In [71]:
# sondan 5. indexten en son elemandan 1 index geride olan sayıya kadar tüm sayıları ayrı bir listede tutma
rule2 = b[-5:-1]
rule2

array([14, 14, 16, 12])

In [72]:
rule2 = b[-5:]
rule2

array([14, 14, 16, 12, 10])

In [75]:
# ilk 6 veri 
rl3 = b[:6]
rl3

array([16, 10, 13, 16, 13, 18])